## Theoretical questions:

### 1. explain the purpose and advantages of numpy in scientific computing and data analysis. How does it enhance Python's capabilities for numeriacl operations?

In [1]:
#Numpy is an open source mathematical and scientific computing library for Python programming tasks. the name Numpy is shorthand for numrical Python . The Numpy library offers a collection of high-level mathematical functions including support for multi_dimensional arrays, masked arrays and matrices. Numpy also including support for muti_dimensional arrays, masked arrays and matrices. NumPy also includes various logicla and mathematical capabilities fo rthose arrays such as shape manipulation, sorting, selection, linear algebra, statistical operations, random number generation and discrete Fourier transforms.
#As with any programmers can easily write Python code that makes calls and exchanges data with NumPy library was first released in 2006. Today, the scientific computing community supports the open source library, and NumPy is currently available through GitHub. Development of the NumPy library is active and ongoing.0


### 2. compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [ ]:
#In the Numpy library, there are two functions np.mean()and np.average()are present. Both are actually doing nearly the same job of calculating mean/average.
#if that is the case then we have to use np.average(). With np.average function we can calculate both arithmetic mean and weighted average. In this article, we have shown the basic use case of both functions and how they are different from each other.
#Difference between np.average()and np.mean()
#np.mean() = 1. use to calculate arithmetic mean
            # 2. all elements have equal weight
           # 3. weith cannot be passed though the parameter of the given function.
           # Syntax: np.mean(arr,axis=None)   where 'arr' is the given array.
#np.average() = 1. use to calculate the arithmetic mean as well as weighted agerage.
            # 2. All elements may or amy not have equal weight.
            # 3.weight can be passed through the parameter of the given function.
            # 4. numpy.average(arr,axis=None, weights=name) Where 'arr' is the the given array

np.mean()
# in numpy library, np.mean() is a function used to calculate arithmetic mean of the given arry along with the axis. Lets see the code implementation.
code
# this code calculates the mean (average) of a NumPy. array named 'arr' and prints both teh array and its mean value.


In [27]:
import numpy as np
arr1=np.array([3,7,8,6,5,4])
arr1

array([3, 7, 8, 6, 5, 4])

In [28]:
np.mean(arr1)

5.5

In [30]:
arr2=np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
np.average(arr2)

4.0

In [34]:
np.average(arr1)

5.5

### 3. Describe the methods for reversing a Numpy array along different axis. Provide examples for 1D and 2D arrays.

In [36]:
#Sometimes while programming in Python, we need to use Pyton to invert a NumPy array. In python, the reverse of a NumPy array indicates changing the order. The first element, the second last, the last the first, and so on. There are several methods for reversing a numpy array.
# some of the most frequent methods for reversing a numpy array are as follows:
# len() with loops ,  flip()function, reverse()function, flipud()function, fliplr()function

In [37]:
def reverse(nums):
    start_index=0
    end_index = len(nums)-1
    while end_index>start_index:
        nums[start_index],nums[end_index]=nums[end_index],nums[start_index]
        start_index = start_index+1
        end_index = end_index-1
n = [1,2,3,4,5,6,7,8,9,0]
reverse(n)
print(n)

[0, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [38]:
import numpy as np
arr = np.array([2,4,6,8,4,9,3,1])
reve_arr = arr[::-1]
print (reve_arr)

[1 3 9 4 8 6 4 2]


### 4. How can you determine the data type of elements in a Numpy array? Discuss the importance of data types in memory management and performance.

In [39]:
#Numpy is a powerful python library. that can manage different types of data. Here we will explore the Datatypes in NumPy and How we can check and create datatypes of the NumPy array. 
# Data Types in NumPyd 
# A data type in NumP{y. is used to specify the type of data stored in a variable. Here is teh list of characters to represent data types available in NumPy.
#   b = boolean, f= float, m= Time delta, o= object, U= unicode string, i= integer, u= unsigned integer, c= Complex float, M= datatime, s= string, v= a fixed chunk of memory fo rother types (void)

In [40]:
import numpy as np
arr= np.array([2,46,6])
arr.dtype

dtype('int32')

In [41]:
arr1= np.array([2,3,"pw",])
arr1.dtype

dtype('<U11')

In [42]:
# in a multiprogramming computer, the operating System resides in a part of memory, and the rest is used by multiple processes. The task of subdividing the memory Management. Memory management is a method in the operating system ot manage operations between main memory and disk durign process execution. The main aim of memory management is to achieve efficient utilllization of memory.
# allocate and de-allocate memory before and after process execution.
#to keep track of used memory space by processes.
#to minimize fragmentation issues.
#to proper utilization of main memory. 
#to maintain data integrity while executing of process.


### 5. create a NumPy array of strings ['python','numpy','pandas']. Apply different case transformations (uppercase, lowercase,title case,etc) to each element.

In [43]:
import numpy as np
arr=np.array(['pwskill','data analytics','priya','july batch'])
arr

array(['pwskill', 'data analytics', 'priya', 'july batch'], dtype='<U14')

In [47]:
uppered_case= np. char. upper(arr)
print("Uppered: ", uppered_case)

Uppered:  ['PWSKILL' 'DATA ANALYTICS' 'PRIYA' 'JULY BATCH']


In [49]:
lowered_case=np.char.lower(arr)
print("Lowered: ", lowered_case)

Lowered:  ['pwskill' 'data analytics' 'priya' 'july batch']


In [51]:
capitalized_case = np.char.capitalize(arr)
print("capitalized: ", capitalized_case)

capitalized:  ['Pwskill' 'Data analytics' 'Priya' 'July batch']


In [52]:
swapcased_case = np.char.swapcase(arr)
print("swapcased: ",swapcased_case)

swapcased:  ['PWSKILL' 'DATA ANALYTICS' 'PRIYA' 'JULY BATCH']


In [53]:
titlecased_case = np.char.title(arr)
print("titlecased: ",titlecased_case)

titlecased:  ['Pwskill' 'Data Analytics' 'Priya' 'July Batch']


### 6. Analyze the performance benefits of numpy arrays over python lists forlarge_scale numerical opertions.

In [57]:
# 1. Speed Boost
#Numpy arrays provide a significant spped advantage over traditional lists. 
#This is because Numpy is built in C and uses optimized,pre-compiled code for numerical operations. this allows for vectorization, which means opertions are applied to all elemetns in an array without the need for explicit loops in python. this not only simplifies your code but also accelerates execution, as vectorized operations are inherently faster than their looped counterparts in high_level languages like python.
#2. memory usage
# When it comes to memory efficiency. Numpy arrays are far superior ot traditional lists. Each item in a numpy array is of the same data type, requiring less memory overhead compared ot python lists where each element can be of a differnet type. 
#Furthermore, Numpy arrays are stored contiguously inmemory, which enhances performance by allowing for efficient access and manipulation of data, particularly beneficial when handling large datasets.
# 3. Advanced Functions
#Numpy comes with a plethora of built_in functions for performing complex mathematical operations, which are not only fasterbut also more reliable than writing yur own functions form scratch.
#these functions cover a wide range of statistical operations.
#the convenience of efficiency of having these advanced functions at your fingertips can greatly accelerate your fingertips can greatly accelerate yur data analysis workflows.
# 4. mutidimensional data
#traditional pytoon lists are not optimized for multidimensional data operations .
# numpy, however, excels in handling such data structures withits multidimensional array(ndarray) support.
# 5. broad compatibility


### 7. compare vstack() and hstack() functions in Numpy. Provide examples demonstrating their usage and output.

In [58]:
# suppose you have a 3*3 array to which you wish you wish to add a row or column. Adding a row is easy with 
# np.vstack:


In [16]:
import numpy as np
arr1 = np.ones((3,3))
arr1


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:

arr2 = np.array([[9,3,3],[2,5,7],[4,6,7]])
arr2

array([[9, 3, 3],
       [2, 5, 7],
       [4, 6, 7]])

In [23]:
np.vstack([arr1,arr2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [9., 3., 3.],
       [2., 5., 7.],
       [4., 6., 7.]])

In [22]:
np.hstack([arr1,arr2])

array([[1., 1., 1., 9., 3., 3.],
       [1., 1., 1., 2., 5., 7.],
       [1., 1., 1., 4., 6., 7.]])

### 8. explain the differences between fliplr() and flipud() methods in numpy, including their effects on various array dimensions.

In [25]:
#flip() you cna flip the Numpy array ndarray vertically (up-down)or horizontally(left-right). There are also numpy.flipud() specialized for vertical flipping and numpy. fliplr() specialized for horizontal flipping.

In [28]:
import numpy as np
a= np.array([[2,5,6],[4,7,8]])
a

array([[2, 5, 6],
       [4, 7, 8]])

In [30]:
np.fliplr(a)

array([[6, 5, 2],
       [8, 7, 4]])

In [31]:
np.flipud(a)

array([[4, 7, 8],
       [2, 5, 6]])

### 9. discuss the functionality of the array_split() method Numpy. How does it handle uneven splits?

In [1]:
#The array_split() method in Numpy is used to devide an array into multiple subarrays. Its primary functionality includes:
# 1. Splitting an Array: It allows you to split an array into a specified number of equal (or nearly equal) sub-arrays along a given axis.
# 2. Flexible Number of Splits: Unlike split(), which requires the number of splits to evenly divide teh array, array_split() can handle cases where the array sixe isn't prerfectly diisible by teh number of splits. In such cases, some sub-array size isn't perfectly divisible by the number of splits. In such cases, some sub-arrays may have onemore element than others.
# 3. Parameters: ary: the input array to be split. 
              # indices_or_sections: This can be an integer (number of splits)or a 1-D array of indices at which to split. 
              # axis: The axis along which to split teh array (default is 0).
# 4. Return Value: It returns a list of sub-arrays.

In [2]:
import numpy as np
a = np.array([1,23,4,5,54,78,98,73,58,34])
a

array([ 1, 23,  4,  5, 54, 78, 98, 73, 58, 34])

In [4]:
np.array_split(a,3)

[array([ 1, 23,  4,  5]), array([54, 78, 98]), array([73, 58, 34])]

### 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?


In [5]:
# numpy arrays are homogeneous in nature means it is an array that contains daa of ta single type only.
#the concept of vectorized operations on Numpy allows teh use of more  optimal and precompiled unctions and mathematical operations on Numpy array objects and  
#data sequences. the output and operations will speed up when compared to simple non-vectorixed operations.


In [7]:
a=np.array([1,5,7,9,3])
b=np.array([2,4,6,8,10])
c=a*b
c

array([ 2, 20, 42, 72, 30])

## practical question

### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [16]:
import numpy as np
arr= np.random.randint(1,100,size=(3,3))
arr

array([[20, 28, 36],
       [68, 19, 32],
       [79, 89, 68]])

In [18]:
arr.T

array([[20, 68, 79],
       [28, 19, 89],
       [36, 32, 68]])

### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [1]:
import numpy as np
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [5]:
import numpy as np
arr= np.random.rand(4,4)
arr

array([[0.81682978, 0.80647564, 0.9789435 , 0.7473897 ],
       [0.23909191, 0.20265139, 0.54309391, 0.00819926],
       [0.24712802, 0.48157918, 0.08752721, 0.08947953],
       [0.04648198, 0.15299785, 0.80664428, 0.37006055]])

In [14]:
arr1= np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("6x6 Array with Zero Border:\n")
print(arr1)

6x6 Array with Zero Border:

[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.81682978 0.80647564 0.9789435  0.7473897  0.        ]
 [0.         0.23909191 0.20265139 0.54309391 0.00819926 0.        ]
 [0.         0.24712802 0.48157918 0.08752721 0.08947953 0.        ]
 [0.         0.04648198 0.15299785 0.80664428 0.37006055 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [17]:
import numpy as np
arr = np.arange(10,60,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.


In [22]:
import numpy as np
arr=np.array(['majiara', 'sainthia','kolkata'])

uppercase=np.char.upper(arr)
lowercase=np.char.lower(arr)
titlecase=np.char.title(arr)

print ("original_array:\n")
print (arr)

print ('uppercase:\n')
print (uppercase)

print ("lowercase:\n")
print (lowercase)

print ("titlecase\n:")
print (titlecase)

original_array:

['majiara' 'sainthia' 'kolkata']
uppercase:

['MAJIARA' 'SAINTHIA' 'KOLKATA']
lowercase:

['majiara' 'sainthia' 'kolkata']
titlecase
:
['Majiara' 'Sainthia' 'Kolkata']


### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [23]:
import numpy as np
arr= np.array([ "kisan","vendon","officer"])
arr

array(['kisan', 'vendon', 'officer'], dtype='<U7')

In [25]:
words_with_space=np.char.join(' ',arr)
print ("words_with_space\n:")
print (words_with_space)

words_with_space
:
['k i s a n' 'v e n d o n' 'o f f i c e r']


### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [37]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

# Print the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [41]:
import numpy as np
identity_matrix = np.eye(5)
diagonal_elements = np.diag(identity_matrix)

print ("identity_matrix:\n")
print(identity_matrix)
print("diagonal_elements:\n")
print(diagonal_elements)

identity_matrix:

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
diagonal_elements:

[1. 1. 1. 1. 1.]


### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.


In [42]:
import numpy as np

# Simplified function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    # Check for factors from 5 to sqrt(n)
    for i in range(5, int(n**0.5) + 1, 6):
        if n % i == 0 or n % (i + 2) == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Find and sort all prime numbers in the array
prime_numbers = np.array(sorted([num for num in random_array if is_prime(num)]))

print("Random Array:")
print(random_array)

print("Sorted Prime Numbers:")
print(prime_numbers)

Random Array:
[133 465 978 157 982 178 877 267 139 162 584 857 835 459 657 862 428 929
 629 648 966 750 736 283 384 563 505 362 285 835 744 313 106 797 809 689
 443 274 895 744 665 921 208 313 528  11 244 431 118  87 868 186 857 404
 224 688 311 170 205 334 624 998 897 550 238 321 753 298 422 976 125 796
 508 242 342 838 339 938 193 655 478 567 603 703 202 896 560 580 439 324
 133 183 140 972 322 864 752 932 813 235]
Sorted Prime Numbers:
[ 11 139 157 193 283 311 313 313 431 439 443 563 797 809 857 857 877 929]


### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.